// نوع العطل / العمل — نفس قائمة نظام الوزارة
// تطلع كأزرار داخل بلاغ قسم التشغيل، وتنطبع في التقرير
export const OPERATIONS_OPTIONS = [
  'عطل داخلي - Internal Fault',
  'فيوز كتاوات - CutOut Fuse',
  'فيوز محطة - Substation Fuse',
  'كتاوات - Cut Out',
  'قاعدة - CutOut Base',
  'كيبل مضروب - Cable Damaged',
  'كيبل محترق - Cable Burnt',
  'انقطاع محطة ثانوية - Secondary S/S Outage',
  'انقطاع كلي - محطة رئيسية - Primary S/S Total Outage',
  'اجزاء مفقودة بمحطة ثانوية - Missing Parts at S/S',
  'نيوترال مسروق - Stolen Neutral',
  'سيرفيس محروق - Burnt Service',
  'عداد محترق - Burnt Meter',
  'رايزر - Rayzer',
  'محول محلي - LTR',
  'UDS',
  'Spur',
  'OHL',
  'PMT',
  'تم تركيب ماكينة - Machine Installed',
  'Joint - محترق',
  'قاطع - Breaker',
  'قاطع - MCCB',
  'اخرى - Other',
];
